### ISSUE TITLE
[Disc] Index. One file at the root, vs. One file per leaf folder

### ISSUE THREAD

**Issue by rido-min** [iotmodels/specs#7]
With the Folder/Name convention, clients can resolve a dtmi without loading the index:

From `dtmi:com:demo:foo:bar:myModel;1` to `dtmi/com/demo/foo/bar/mymodel-1.json`

# Why we need the index ?

Even with the convention converting  DTMI to `lowerCase` folder names, there are cases where the case sensitive wants to be preserved.

```
dtmi:com:demo:foo:bar:myModel;1 -> dtmi/com/demo/foo/bar/mymodel-1.json
dtmi:com:demo:foo:bar:mymodel;2 -> dtmi/com/demo/foo/bar/mymodel-2.json

resolve('dtmi:com:demo:foo:bar:mymodel;1') // 404
```

But we could also create this mapping file in each folder without going to a big centralfile.

## DTMIs must be case sensitive unique 

- Using a single JSON map provides unique case sensitive keys.
- The ingestion process could use this file to detect issues with conflicting DTMIs with different case.

## Iterate over all available DTMI

- Without any UX in the model repo (beyond the default GitHub repo Web UI), without the index will not possible to find any model without knowing the DTMI in advance
- Clients can query the index to find if a model exists, instead of relying on http 404 status
- Enables to download the complete repo by iterating this file
- Enables to reuse the same index format when caching models in the local folder

## Dependencies

Storing the dependencies in the index will enable to download a given model without parsing the contents of the file.

# One (big) central file or multiple (small) index per folder

We can break down the index in one file per folder, this index will contain the case sensitive DTMI for the folder, and the dependencies. 

## Comparision

|     |OneFile|MultipleFiles|
|---|---|--------------|
|Pros| Easy to look for IDs without 404 or `File.Exists`| Scales better without wondering for the file size |
|Cons| Need to specify file size limits, n of entries, file size| Need to traverse the folder (specially costly with nested folders)|

**Comment by montgomp** [comment]
The first example call to `resolve('dtmi:com:demo:foo:bar:mymodel;1') // 404` failing is possible if the resolver checks that the dtmi in the root `@id` property is an exact match of what was passed in. This could all be done without an index file and would reduce the number of http requests.

Case sensitive DTMI, since we are enforcing a case-insensitive folder structure and file name (forced lower-case) based on the DTMI, the ingestion process doesn't need this. Only one file can possibly exist at a given path.

Iterate DTMI - GitHub web UI has a search in the upper left. We don't need an index to allow searching for model attributes. The index gives us nothing here. Clients querying index have to be aware that index may not be in sync. This is especially true of private clones of the repo without a GitHub action to update index post commit. The same reason you said not to rely on `/blob/commit_hash/`.  Downloading the complete repo is possible by doing `git clone`. No need for index in local folder for the same reason. Either the file is there or it isn't.

Dependencies - moving this out to a known file path `dtmi/com/demo/foo/bar/mymodel-1.dependencies //as a text file (delimited with ; or \n` means we also don't need to have an index file.

**Comment by rido-min** [comment]
1) we can check if the id is the same only after we download the file. That solution requires to download an unwanted file. I'm trying to be prepared to answer the case sensitive question, specially at ingestion time.

2) Yes, but you will never know if the lower case path contains the CaseSensitive or not. 

3) We can't think GitHub as a solution for browsing, private repos might not have that. The index must to be in sync always (if not, is not an index). I would not rely in `git clone` to get models, specially for partial ones. 

4) Yes, we can move deps to an inner folder, but that will require multiple file downloads to resolve.

I'm thinking about the index as a snapshot to improve the search experience. If you only have the `dtmi` root folder, you will need to traverse the full tree to find if that file exists.

Again, this is not mandatory, just a helper artifact to improve these points.

The main CON seems to be the file size, I think that package-lock.json shows that this is doable.

**Comment by rido-min** [comment]
When thinking how to validate models we will need to traverse the `dtmi` folder to get all the paths in the dependency tree to give them to the parser. 

I believe we will need this structure during validation, so we are moving the problem to the user. Having a trustable index in a JSON map ahead of time allows to "cache" the deps tree.

**Comment by montgomp** [comment]
> 1. we can check if the id is the same only after we download the file. That solution requires to download an unwanted file. I'm trying to be prepared to answer the case sensitive question, specially at ingestion time.

And downloading a model-index.json is also downloading an unwanted file (I just want the model). Ingestion still does not need an index. Period.

> 2. Yes, but you will never know if the lower case path contains the CaseSensitive or not.

Good. I think we're in agreement then. There is no need for the index for ingestion because you don't need to know the casing of the file you are *currently* authoring because you are *currently* authoring it. Resolution would check that the document(s) it received is/are valid DTDL (including matching the casing of the DTMI).

> 3. We can't think GitHub as a solution for browsing, private repos might not have that. The index must to be in sync always (if not, is not an index). I would not rely in `git clone` to get models, specially for partial ones.

Ok, then file explorer, it allows searching for file contents. VSCode allows searching file contents. `grep -rnw '/somepath' -e 'mypattern'` allows searching file contents. I'm not sure what you are referring to as "partial" models, can you elaborate?
> 4. Yes, we can move deps to an inner folder, but that will require multiple file downloads to resolve.
> 

I agree. Let's only store DTDL and resolve dependencies as they are found in parsing those documents on the return.

> I'm thinking about the index as a snapshot to improve the search experience. If you only have the `dtmi` root folder, you will need to traverse the full tree to find if that file exists.

You said in your above point 3 that we can't rely on GitHub but the only way that we've mentioned this snapshot getting updated is via GitHub actions. Private repos won't have this capability and therefore can't be in scope or we can't have index and dependencies as external files. We need consistency here.
> Again, this is not mandatory, just a helper artifact to improve these points.
> 
> The main CON seems to be the file size, I think that package-lock.json shows that this is doable.

The functionality of package-lock.json (or npm-shrinkwrap.json) is completely different. I think the main CONs with the index are its existence, force reliance (we don't need it), and inconsistent update methodologies (GitHub actions versus manual intervention).

**Comment by montgomp** [comment]
> When thinking how to validate models we will need to traverse the `dtmi` folder to get all the paths in the dependency tree to give them to the parser.
> 
> I believe we will need this structure during validation, so we are moving the problem to the user. Having a trustable index in a JSON map ahead of time allows to "cache" the deps tree.

When do you foresee this becoming the users problem? IE, when is the user going to have to perform this validation?

The phrase "trustable index" is very misleading here. The only way that we can assure that it is a trustable index is if we disallow forks, clones, offline scenarios. Otherwise, it is a manual intervention and therefore subject to breakage. 

Also, I'd like to know more about the "ahead of time" scenario. If the plan is to make a cache of all the dependencies of unknown requests, clone the whole repo because you'll always be chasing corner cases of some unknown dependency.

**Comment by rido-min** [comment]
OK, let's remove the `model-index` from the spec. We will require ONLY the folder/filename structure we agreed
